update data format for  graph
PaddlePaddle/VisualDL pull request #32
Opened 2017-12-27 07:43 UTC by deqingli

2017-12-27 07:45 UTC, jacquesqiao commented on docs/graph_data_format.md
> +        {"source": "x", "target": "1"},
把label也加上吧

2017-12-27 07:46 UTC, deqingli commented on docs/graph_data_format.md
> +        {"source": "x", "target": "1"},
我竟然忘了，失误

2017-12-27 08:01 UTC, jacquesqiao submitted a review, later dismissed
LGTM! please @daming-lu review ~

2017-12-27 08:11 UTC, daming-lu submitted a review, later dismissed

2017-12-27 08:11 UTC, daming-lu commented on docs/graph_data_format.md
> +        {"source": "x", "target": "1", "label": "label1"},
'X' 应该大写

2017-12-27 08:11 UTC, daming-lu commented on docs/graph_data_format.md
> +                "1"
是否应该用至少二维维度？这样更generic？比如：

W1: 3 x 2
X: 2 x 1
B1: 3 x 1

？

2017-12-27 08:13 UTC, jacquesqiao commented on docs/graph_data_format.md
> +                "1"
shape是一个vector, 比如 [1,2,3]就代表 1 X 2 X 3的三维举证，vector<int>足够表达任意维度了

2017-12-27 08:51 UTC, jacquesqiao commented on docs/graph_data_format.md
> +                "1"
不好意思，我误解了，确实shape多几个维度更有代表性

2017-12-28 07:12 UTC, daming-lu requested changes

2017-12-28 07:12 UTC, daming-lu commented on docs/graph_data_format.md
> +        {"source": "X", "target": "1", "label": "label1"},
1) 我们可以把 source -> from, target -> to
2) 这个例子漏掉了从node出来的边，比如，第一个node有4条边
W1 -> node_0
B1 -> node_0
X -> node_0
node_0 -> H1 (出边漏掉了!)
3) 用名字 ”X" 不知道方不方便？ 我想可以用 类型+下标，比如 input_0, node_1 。看看前端怎么render方便。个人感觉如果用名字 “X"，”W2" 什么的，则需要用 map 来加速查找。既然我们已经有 array了，用下标比较方便。

2017-12-28 07:20 UTC, deqingli commented on docs/graph_data_format.md
> +        {"source": "X", "target": "1", "label": "label1"},
1. 这个名称就不改了，之前的可视化，edge 都是 target， source。
2. 理解是 "H1" 的作用就是连接 node 1 , node2.
3. 这个name 是作为 keyid的，用来查找node，后端怎么取都行。

2018-01-08 07:01 UTC, jacquesqiao submitted a review, later dismissed
LGTM

2018-01-11 05:44 UTC, closed without merging