Add histogram
PaddlePaddle/VisualDL pull request #652
Opened 2020-06-05 02:41 UTC by ShenYuhan

1 add histogram.
2 add hd file system.

2020-06-05 03:24 UTC, ZeyuChen requested changes
HDFS这里后续需要完善。是否可以让用户支持logdir那里直接传入hdfs链接，看上去这里还没完全打通。

2020-06-05 03:24 UTC, ZeyuChen commented on visualdl/io/bfile.py
> +        self.cli = hdfs.Client("http://182.61.50.230:50070")
这个IP地址适合暴露吗？

2020-06-05 03:24 UTC, ZeyuChen commented on visualdl/io/bfile.py
> +        self.cli = hdfs.Client("http://182.61.50.230:50070")
是否改成127.0.0.1

2020-06-05 03:24 UTC, ZeyuChen commented on visualdl/io/bfile.py
> +        self.cli = hdfs.Client("http://182.61.50.230:50070")
按理应该得有hdfs的目录链接才行

2020-06-08 12:18 UTC, nepeplwu commented on visualdl/io/bfile.py
> +        self.cli = hdfs.Client("http://182.61.50.230:50070")
用户需要如何配置ugi？是否可以通过以下方式写入和读取？
```python
from visualdl import LogWriter
with LogWriter(logdir="hdfs://xxxxxxxxxxxxxx") as writer:
    pass
```
```shell
visualdl --logdir hdfs://xxxxxxxxxxxxxx
```

2020-06-08 12:18 UTC, nepeplwu commented on visualdl/server/lib.py
> +        results.append([item.timestamp, item.id, histogram_data])
是否也需要做个蓄水池抽样？

2020-06-08 12:50 UTC, ShenYuhan commented on visualdl/server/lib.py
> +        results.append([item.timestamp, item.id, histogram_data])
这里已经是抽过样的了，最多显示100个，和之前的版本保持一致

2020-06-08 12:51 UTC, ShenYuhan commented on visualdl/io/bfile.py
> +        self.cli = hdfs.Client("http://182.61.50.230:50070")
确实是通过这种方式来写入和读取的，靠路径名前缀区分所用的文件系统。

2020-06-09 06:15 UTC, closed without merging