Correct QQ Number
PaddlePaddle/VisualDL pull request #925
Opened 2021-02-02 14:47 UTC by YixinKristy

2021-02-02 15:25 UTC, PeterPanZH requested changes

2021-02-02 15:25 UTC, PeterPanZH commented on docs/faq.md
> +由于目前VisualDL已经不维护python2了，且现有官方文档上的使用说明都是基于2.0版本的，也不维护旧版本了建议升级至python3，安装最新版的VisualDL，即不会出现上述问题。
是不是少了个标点符号。。

2021-02-03 01:27 UTC, linhandev commented
![image](https://user-images.githubusercontent.com/29757093/106684730-fcf75480-6601-11eb-8e9d-faabf78b8b38.png)

docs/README-en.md 里应该是也有这个错误的群号

2021-02-03 02:36 UTC, YixinKristy commented on docs/faq.md
> +由于目前VisualDL已经不维护python2了，且现有官方文档上的使用说明都是基于2.0版本的，也不维护旧版本了建议升级至python3，安装最新版的VisualDL，即不会出现上述问题。
已改~

2021-02-03 03:08 UTC, merged